// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	redis "github.com/go-redis/redis/v8"
	mock "github.com/stretchr/testify/mock"
)

// Redis is an autogenerated mock type for the Redis type
type Redis struct {
	mock.Mock
}

// GetClient provides a mock function with given fields:
func (_m *Redis) GetClient() *redis.Client {
	ret := _m.Called()

	var r0 *redis.Client
	if rf, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}

	return r0
}

type mockConstructorTestingTNewRedis interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedis creates a new instance of Redis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedis(t mockConstructorTestingTNewRedis) *Redis {
	mock := &Redis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
