version: "3.8"

services:
  user_service:
    container_name: user_service
    build: ./user
    ports:
      - 8080:8080
  book_service:
    container_name: book_service
    build: ./book
    ports:
      - 8081:8081
  notification_service:
    container_name: notification_service
    build: ./notification
    ports:
      - 8082:8082
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=leomessi
    volumes:
      - ./volumes/mongodb:/data/db