version: "3.8"

services:
  # user_service:
  #   container_name: user_service
  #   build: ./user
  #   ports:
  #     - 8080:8080
  # book_service:
  #   container_name: book_service
  #   build: ./book
  #   ports:
  #     - 8081:8081
  # notification_service:
  #   container_name: notification_service
  #   build: ./notification
  #   ports:
  #     - 8082:8082
  mongodb:
    container_name: book_mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=leomessi
    volumes:
      - ./volumes/mongodb:/data/db

  zookeeper:
    container_name: book_zookeeper
    image: bitnami/zookeeper:3.6.2
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - zk_id=1

  redis:
    container_name: book_redis
    image: redis:6.0.9
    command: redis-server --requirepass leomessi --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data

  kafka:
    container_name: book_kafka
    image: bitnami/kafka:2.6.0
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes: 
      - ./volumes/kafka:/var/lib/kafka/data